### ISSUE TITLE
识别错误，识别出来不是对应的音频，专辑识别点那个按钮没反应

### ISSUE THREAD

**Issue by Mario-Hero** [FEYeh/ximalayadownloader#3]
识别错误，识别出来不是对应的音频，专辑识别点那个按钮没反应
![image](https://user-images.githubusercontent.com/8732457/150513785-21fe87eb-fe3a-49ba-a771-748a1a6405e3.png)

**Comment by FEYeh** [comment]
单个识别需要在单个音频页面
专辑识别已修复
