### ISSUE TITLE
每天下载的集数有限制吗，是大佬设置的限制还是喜马的限制呢

### ISSUE THREAD

**Issue by 17764591637** [FEYeh/ximalayadownloader#4]
每天下载的集数有限制吗，是大佬设置的限制还是喜马的限制呢。
昨天试了一下，每天最多下载600集，登录的VIP账号

**Comment by cj-neo** [comment]
> 每天下载的集数有限制吗，是大佬设置的限制还是喜马的限制呢。 昨天试了一下，每天最多下载600集，登录的VIP账号

我替大老回答，这个是喜马拉雅网页版的限制，所以下载非 VIP 的资源不要登入帐号下载，必要才登入，额度要花在刀口上 XD

**Comment by 17764591637** [comment]
> 

好的  多谢
